### ISSUE TITLE
Outline path overlaps exposed using webkit-text-stroke

### ISSUE THREAD

**Issue by badcat** [huertatipografica/piazzolla#17]
Love this font!  But when using the  -webkit-text-stroke property I see the stoke overlaps falling inside of the fill. Here's an example.  

<img width="617" alt="piazzolla-text-stroke" src="https://user-images.githubusercontent.com/26096/96754828-d2a9c000-139f-11eb-875c-0c04b13c260f.png">

Is there another approach?
I currently have the CSS like this..
`h1 {
    font-family: 'Piazzolla', serif;  
    font-weight: 800;  
    font-size: 8rem;  
    color: rgb(179 255 0);  
    -webkit-text-fill-color: rgb(179 255 0);  
    -webkit-text-stroke: 2px rgb(0 0 0);  
}
`

**EDIT:**  I suppose I could use the simlated stroke like this for the moment - still it would be nice to use the newer properties.

`
h1 {
    font-family: 'Piazzolla', serif;  
    font-weight: 800;  
    font-size: 8rem;  
    color:rgb(179 255 0);
    text-shadow:
     -1px -1px 0 #000,  
      1px -1px 0 #000,
      -1px 1px 0 #000,
       1px 1px 0 #000;
  }
`

**Comment by juandelperal** [comment]
Hello @badcat
The contours of variable fonts require the drawings to be different than what it would be "normal" for static fonts. This is for improve the drawings interpolated between the extremes. That's why you see this kind of overlapping. 
So, yes, you could either use `text-shadow` or switch to static fonts, which have the paths already merged.

All the best

**Comment by badcat** [comment]
Ahh.  ok, thanks for sharing.  Always much to learn. Maybe we'll get some new CSS properties for variable font outline styles. 🤞
