### ISSUE TITLE
Fonts missing from repo

### ISSUE THREAD

**Issue by yanone** [huertatipografica/piazzolla#7]
Google Fonts requires the fonts to be existent in the repository.

**Comment by juandelperal** [comment]
Fonts are being generated via CI: that way the repo just keep the working files and the fonts are always synced with the sources. 
Binaries are here https://github.com/huertatipografica/piazzolla/releases

I think that way is better, but I'm open to change it if needed.
(It takes a LOT of time to generate the fonts, at least in my computer, that's why I put github to make that part for me)
